import { db } from "./db";
import { artisans } from "@shared/schema";

const gautengArtisans = [
  // Johannesburg Artisans
  {
    firstName: "Sipho",
    lastName: "Mthembu",
    email: "sipho.mthembu.sandton@email.com",
    phone: "+27 82 456 7890",
    location: "Sandton, Johannesburg",
    services: ["builders"],
    description: "Professional construction specialist with 12 years experience in luxury residential projects.",
    yearsExperience: 12,
    rating: "4.7",
    reviewCount: 28,
    verified: true,
    profileImage: "SM",
    portfolio: [],
    idDocument: "verified_id_101.pdf",
    qualificationDocuments: ["nhbrc_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "All documents verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Nomsa",
    lastName: "Radebe",
    email: "nomsa.radebe@email.com",
    phone: "+27 83 567 8901",
    location: "Rosebank, Johannesburg",
    services: ["cleaners"],
    description: "Eco-friendly cleaning services for homes and offices. Specialized in post-construction cleanup.",
    yearsExperience: 8,
    rating: "4.9",
    reviewCount: 45,
    verified: true,
    profileImage: "NR",
    portfolio: [],
    idDocument: "verified_id_102.pdf",
    qualificationDocuments: ["cleaning_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Excellent credentials",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Thabo",
    lastName: "Mokoena",
    email: "thabo.mokoena@email.com",
    phone: "+27 84 678 9012",
    location: "Soweto, Johannesburg",
    services: ["electricians"],
    description: "Licensed electrician specializing in solar installations and smart home systems.",
    yearsExperience: 15,
    rating: "4.8",
    reviewCount: 52,
    verified: true,
    profileImage: "TM",
    portfolio: [],
    idDocument: "verified_id_103.pdf",
    qualificationDocuments: ["electrical_license.pdf", "solar_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Solar specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Zanele",
    lastName: "Ndlovu",
    email: "zanele.ndlovu@email.com",
    phone: "+27 85 789 0123",
    location: "Alexandra, Johannesburg",
    services: ["landscapers"],
    description: "Garden design and maintenance specialist. Expert in indigenous South African plants.",
    yearsExperience: 10,
    rating: "4.6",
    reviewCount: 33,
    verified: true,
    profileImage: "ZN",
    portfolio: [],
    idDocument: "verified_id_104.pdf",
    qualificationDocuments: ["horticulture_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Landscape expertise confirmed",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Johannes",
    lastName: "Van Der Merwe",
    email: "johannes.vandermerwe@email.com",
    phone: "+27 86 890 1234",
    location: "Melville, Johannesburg",
    services: ["carpenters"],
    description: "Custom furniture maker and carpentry specialist. 20 years of fine woodworking experience.",
    yearsExperience: 20,
    rating: "4.9",
    reviewCount: 67,
    verified: true,
    profileImage: "JV",
    portfolio: [],
    idDocument: "verified_id_105.pdf",
    qualificationDocuments: ["carpentry_cert.pdf", "furniture_design.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Master craftsman verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Lerato",
    lastName: "Mashego",
    email: "lerato.mashego@email.com",
    phone: "+27 87 901 2345",
    location: "Randburg, Johannesburg",
    services: ["plumbers"],
    description: "Professional plumber specializing in bathroom renovations and water-saving installations.",
    yearsExperience: 14,
    rating: "4.7",
    reviewCount: 39,
    verified: true,
    profileImage: "LM",
    portfolio: [],
    idDocument: "verified_id_106.pdf",
    qualificationDocuments: ["plumbing_license.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Licensed professional",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Mandla",
    lastName: "Dlamini",
    email: "mandla.dlamini@email.com",
    phone: "+27 88 012 3456",
    location: "Midrand, Johannesburg",
    services: ["tilers"],
    description: "Expert tiler with specialization in natural stone and luxury bathroom installations.",
    yearsExperience: 11,
    rating: "4.8",
    reviewCount: 41,
    verified: true,
    profileImage: "MD",
    portfolio: [],
    idDocument: "verified_id_107.pdf",
    qualificationDocuments: ["tiling_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Stone specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Precious",
    lastName: "Mahlangu",
    email: "precious.mahlangu@email.com",
    phone: "+27 89 123 4567",
    location: "Fourways, Johannesburg",
    services: ["cleaners"],
    description: "Premium cleaning services for luxury homes and corporate offices. Green cleaning products only.",
    yearsExperience: 7,
    rating: "4.9",
    reviewCount: 55,
    verified: true,
    profileImage: "PM",
    portfolio: [],
    idDocument: "verified_id_108.pdf",
    qualificationDocuments: ["cleaning_cert.pdf", "eco_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Eco-certified professional",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Sizani",
    lastName: "Mabena",
    email: "sizani.mabena@email.com",
    phone: "+27 80 234 5678",
    location: "Roodepoort, Johannesburg",
    services: ["builders"],
    description: "Renovation specialist focusing on kitchen and bathroom remodeling projects.",
    yearsExperience: 16,
    rating: "4.6",
    reviewCount: 44,
    verified: true,
    profileImage: "SM",
    portfolio: [],
    idDocument: "verified_id_109.pdf",
    qualificationDocuments: ["building_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Renovation expert verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Themba",
    lastName: "Sithole",
    email: "themba.sithole@email.com",
    phone: "+27 81 345 6789",
    location: "Germiston, Johannesburg",
    services: ["electricians"],
    description: "Industrial and residential electrician. Certified for high-voltage installations.",
    yearsExperience: 18,
    rating: "4.8",
    reviewCount: 62,
    verified: true,
    profileImage: "TS",
    portfolio: [],
    idDocument: "verified_id_110.pdf",
    qualificationDocuments: ["electrical_license.pdf", "hv_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "High voltage certified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Beauty",
    lastName: "Nkomo",
    email: "beauty.nkomo@email.com",
    phone: "+27 82 456 7890",
    location: "Benoni, Johannesburg",
    services: ["landscapers"],
    description: "Garden maintenance and landscape design. Specialist in water-wise gardens and indigenous plants.",
    yearsExperience: 9,
    rating: "4.7",
    reviewCount: 36,
    verified: true,
    profileImage: "BN",
    portfolio: [],
    idDocument: "verified_id_111.pdf",
    qualificationDocuments: ["landscaping_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Water-wise specialist",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Mpho",
    lastName: "Molefe",
    email: "mpho.molefe@email.com",
    phone: "+27 83 567 8901",
    location: "Edenvale, Johannesburg",
    services: ["carpenters"],
    description: "Built-in cupboards and kitchen cabinet specialist. Custom woodwork for modern homes.",
    yearsExperience: 13,
    rating: "4.8",
    reviewCount: 48,
    verified: true,
    profileImage: "MM",
    portfolio: [],
    idDocument: "verified_id_112.pdf",
    qualificationDocuments: ["carpentry_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Cabinet specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Nthabiseng",
    lastName: "Tshabalala",
    email: "nthabiseng.tshabalala@email.com",
    phone: "+27 84 678 9012",
    location: "Kempton Park, Johannesburg",
    services: ["plumbers"],
    description: "Emergency plumbing services and water system installations. Available 24/7 for urgent repairs.",
    yearsExperience: 12,
    rating: "4.9",
    reviewCount: 58,
    verified: true,
    profileImage: "NT",
    portfolio: [],
    idDocument: "verified_id_113.pdf",
    qualificationDocuments: ["plumbing_license.pdf", "emergency_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Emergency service certified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Sello",
    lastName: "Madonsela",
    email: "sello.madonsela@email.com",
    phone: "+27 85 789 0123",
    location: "Boksburg, Johannesburg",
    services: ["tilers"],
    description: "Commercial and residential tiling specialist. Expert in large-scale shopping center projects.",
    yearsExperience: 17,
    rating: "4.7",
    reviewCount: 53,
    verified: true,
    profileImage: "SM",
    portfolio: [],
    idDocument: "verified_id_114.pdf",
    qualificationDocuments: ["tiling_cert.pdf", "commercial_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Commercial specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Palesa",
    lastName: "Mokwena",
    email: "palesa.mokwena@email.com",
    phone: "+27 86 890 1234",
    location: "Johannesburg CBD, Johannesburg",
    services: ["cleaners"],
    description: "Corporate office cleaning and maintenance. Specialized in high-rise building cleaning services.",
    yearsExperience: 11,
    rating: "4.8",
    reviewCount: 47,
    verified: true,
    profileImage: "PM",
    portfolio: [],
    idDocument: "verified_id_115.pdf",
    qualificationDocuments: ["cleaning_cert.pdf", "safety_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Safety certified professional",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },

  // Ekurhuleni Artisans
  {
    firstName: "Lucky",
    lastName: "Chabalala",
    email: "lucky.chabalala@email.com",
    phone: "+27 87 901 2345",
    location: "Springs, Ekurhuleni",
    services: ["builders"],
    description: "Residential construction and home additions specialist. Expert in modern architectural designs.",
    yearsExperience: 14,
    rating: "4.6",
    reviewCount: 35,
    verified: true,
    profileImage: "LC",
    portfolio: [],
    idDocument: "verified_id_201.pdf",
    qualificationDocuments: ["building_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Modern design specialist",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Nosipho",
    lastName: "Mthethwa",
    email: "nosipho.mthethwa@email.com",
    phone: "+27 88 012 3456",
    location: "Alberton, Ekurhuleni",
    services: ["electricians"],
    description: "Residential and light commercial electrical work. Certified for smart home automation systems.",
    yearsExperience: 10,
    rating: "4.7",
    reviewCount: 42,
    verified: true,
    profileImage: "NM",
    portfolio: [],
    idDocument: "verified_id_202.pdf",
    qualificationDocuments: ["electrical_license.pdf", "smart_home_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Smart home certified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Bongani",
    lastName: "Khumalo",
    email: "bongani.khumalo@email.com",
    phone: "+27 89 123 4567",
    location: "Benoni, Ekurhuleni",
    services: ["plumbers"],
    description: "Pool installation and maintenance specialist. Expert in water feature construction.",
    yearsExperience: 13,
    rating: "4.8",
    reviewCount: 38,
    verified: true,
    profileImage: "BK",
    portfolio: [],
    idDocument: "verified_id_203.pdf",
    qualificationDocuments: ["plumbing_license.pdf", "pool_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Pool specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Dineo",
    lastName: "Modise",
    email: "dineo.modise@email.com",
    phone: "+27 80 234 5678",
    location: "Daveyton, Ekurhuleni",
    services: ["landscapers"],
    description: "Urban garden design and vertical gardening specialist. Expert in small space solutions.",
    yearsExperience: 8,
    rating: "4.9",
    reviewCount: 31,
    verified: true,
    profileImage: "DM",
    portfolio: [],
    idDocument: "verified_id_204.pdf",
    qualificationDocuments: ["landscaping_cert.pdf", "urban_design.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Urban specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Thembi",
    lastName: "Nhlapo",
    email: "thembi.nhlapo@email.com",
    phone: "+27 81 345 6789",
    location: "Germiston, Ekurhuleni",
    services: ["carpenters"],
    description: "Restoration carpenter specializing in antique furniture repair and historical building restoration.",
    yearsExperience: 19,
    rating: "4.8",
    reviewCount: 56,
    verified: true,
    profileImage: "TN",
    portfolio: [],
    idDocument: "verified_id_205.pdf",
    qualificationDocuments: ["carpentry_cert.pdf", "restoration_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Restoration expert verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Kenneth",
    lastName: "Mbeki",
    email: "kenneth.mbeki@email.com",
    phone: "+27 82 456 7890",
    location: "Boksburg, Ekurhuleni",
    services: ["tilers"],
    description: "Industrial floor tiling and epoxy coating specialist. Expert in warehouse and factory flooring.",
    yearsExperience: 15,
    rating: "4.7",
    reviewCount: 49,
    verified: true,
    profileImage: "KM",
    portfolio: [],
    idDocument: "verified_id_206.pdf",
    qualificationDocuments: ["tiling_cert.pdf", "industrial_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Industrial specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Refilwe",
    lastName: "Seroke",
    email: "refilwe.seroke@email.com",
    phone: "+27 83 567 8901",
    location: "Kempton Park, Ekurhuleni",
    services: ["cleaners"],
    description: "Medical facility and laboratory cleaning specialist. Certified in biohazard cleanup procedures.",
    yearsExperience: 12,
    rating: "4.9",
    reviewCount: 43,
    verified: true,
    profileImage: "RS",
    portfolio: [],
    idDocument: "verified_id_207.pdf",
    qualificationDocuments: ["cleaning_cert.pdf", "biohazard_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Medical facility certified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Vusi",
    lastName: "Mnguni",
    email: "vusi.mnguni@email.com",
    phone: "+27 84 678 9012",
    location: "Edenvale, Ekurhuleni",
    services: ["builders"],
    description: "Commercial building construction and office fitouts. Specialist in modern office environments.",
    yearsExperience: 16,
    rating: "4.6",
    reviewCount: 40,
    verified: true,
    profileImage: "VM",
    portfolio: [],
    idDocument: "verified_id_208.pdf",
    qualificationDocuments: ["building_cert.pdf", "commercial_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Commercial construction verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Nomthandazo",
    lastName: "Zulu",
    email: "nomthandazo.zulu@email.com",
    phone: "+27 85 789 0123",
    location: "Brakpan, Ekurhuleni",
    services: ["electricians"],
    description: "Mining electrical systems specialist. Certified for underground electrical installations.",
    yearsExperience: 20,
    rating: "4.8",
    reviewCount: 61,
    verified: true,
    profileImage: "NZ",
    portfolio: [],
    idDocument: "verified_id_209.pdf",
    qualificationDocuments: ["electrical_license.pdf", "mining_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Mining specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Siphiwe",
    lastName: "Nkosi",
    email: "siphiwe.nkosi@email.com",
    phone: "+27 86 890 1234",
    location: "Nigel, Ekurhuleni",
    services: ["landscapers"],
    description: "Sports field and recreational area landscaping specialist. Expert in cricket and soccer field maintenance.",
    yearsExperience: 11,
    rating: "4.7",
    reviewCount: 34,
    verified: true,
    profileImage: "SN",
    portfolio: [],
    idDocument: "verified_id_210.pdf",
    qualificationDocuments: ["landscaping_cert.pdf", "sports_turf_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Sports turf specialist",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Given",
    lastName: "Mathebula",
    email: "given.mathebula@email.com",
    phone: "+27 87 901 2345",
    location: "Tembisa, Ekurhuleni",
    services: ["carpenters"],
    description: "School furniture and educational facility carpentry specialist. Expert in durable classroom furniture.",
    yearsExperience: 14,
    rating: "4.8",
    reviewCount: 45,
    verified: true,
    profileImage: "GM",
    portfolio: [],
    idDocument: "verified_id_211.pdf",
    qualificationDocuments: ["carpentry_cert.pdf", "education_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Educational specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Thandiwe",
    lastName: "Vilakazi",
    email: "thandiwe.vilakazi@email.com",
    phone: "+27 88 012 3456",
    location: "Duduza, Ekurhuleni",
    services: ["plumbers"],
    description: "Green plumbing solutions specialist. Expert in rainwater harvesting and greywater systems.",
    yearsExperience: 9,
    rating: "4.9",
    reviewCount: 37,
    verified: true,
    profileImage: "TV",
    portfolio: [],
    idDocument: "verified_id_212.pdf",
    qualificationDocuments: ["plumbing_license.pdf", "green_plumbing.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Green systems specialist",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Bheki",
    lastName: "Hadebe",
    email: "bheki.hadebe@email.com",
    phone: "+27 89 123 4567",
    location: "Thokoza, Ekurhuleni",
    services: ["tilers"],
    description: "Heritage building tiling restoration specialist. Expert in historical tile patterns and materials.",
    yearsExperience: 18,
    rating: "4.7",
    reviewCount: 52,
    verified: true,
    profileImage: "BH",
    portfolio: [],
    idDocument: "verified_id_213.pdf",
    qualificationDocuments: ["tiling_cert.pdf", "heritage_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Heritage specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Nkosana",
    lastName: "Mhlongo",
    email: "nkosana.mhlongo@email.com",
    phone: "+27 80 234 5678",
    location: "Katlehong, Ekurhuleni",
    services: ["cleaners"],
    description: "Event and venue cleaning specialist. Expert in pre and post-event cleanup for large venues.",
    yearsExperience: 10,
    rating: "4.8",
    reviewCount: 41,
    verified: true,
    profileImage: "NM",
    portfolio: [],
    idDocument: "verified_id_214.pdf",
    qualificationDocuments: ["cleaning_cert.pdf", "event_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Event specialist verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Busisiwe",
    lastName: "Maseko",
    email: "busisiwe.maseko@email.com",
    phone: "+27 81 345 6789",
    location: "Vosloorus, Ekurhuleni",
    services: ["builders"],
    description: "Affordable housing construction specialist. Expert in RDP housing and community development projects.",
    yearsExperience: 13,
    rating: "4.6",
    reviewCount: 39,
    verified: true,
    profileImage: "BM",
    portfolio: [],
    idDocument: "verified_id_215.pdf",
    qualificationDocuments: ["building_cert.pdf", "rdp_cert.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Community development verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  }
];

const sampleArtisans = [
  {
    firstName: "Thabo",
    lastName: "Mthembu",
    email: "thabo.mthembu@email.com",
    phone: "+27 82 123 4567",
    location: "Johannesburg, Gauteng",
    services: ["builders"],
    description: "15+ years of experience in residential and commercial construction. Specialized in home renovations and extensions.",
    yearsExperience: 15,
    rating: "4.8",
    reviewCount: 32,
    verified: true,
    profileImage: "TM",
    portfolio: [],
    idDocument: "verified_id_001.pdf",
    qualificationDocuments: ["nhbrc_certificate.pdf", "construction_diploma.pdf"],
    verificationStatus: "approved",
    verificationNotes: "All documents verified successfully",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Sarah",
    lastName: "Khumalo",
    email: "sarah.khumalo@email.com",
    phone: "+27 84 567 8901",
    location: "Cape Town, Western Cape",
    services: ["electricians"],
    description: "Certified electrician with expertise in smart home installations, electrical repairs, and energy-efficient solutions.",
    yearsExperience: 8,
    rating: "4.9",
    reviewCount: 28,
    verified: true,
    profileImage: "SK",
    portfolio: [],
    idDocument: "verified_id_002.pdf",
    qualificationDocuments: ["electrical_trade_cert.pdf", "coc_certificate.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Electrical trade certificate verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Mike",
    lastName: "Naidoo",
    email: "mike.naidoo@email.com",
    phone: "+27 83 234 5678",
    location: "Durban, KwaZulu-Natal",
    services: ["plumbers"],
    description: "Professional plumber specializing in bathroom renovations, leak repairs, and hot water system installations.",
    yearsExperience: 12,
    rating: "4.7",
    reviewCount: 41,
    verified: true,
    profileImage: "MN",
    portfolio: [],
    idDocument: "verified_id_003.pdf",
    qualificationDocuments: ["plumbing_certificate.pdf", "iopsa_membership.pdf"],
    verificationStatus: "approved",
    verificationNotes: "IOPSA membership confirmed",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "Nomsa",
    lastName: "Dlamini",
    email: "nomsa.dlamini@email.com",
    phone: "+27 81 345 6789",
    location: "Pretoria, Gauteng",
    services: ["cleaners"],
    description: "Professional cleaning service with eco-friendly products. Specializing in deep cleaning and maintenance.",
    yearsExperience: 6,
    rating: "4.6",
    reviewCount: 23,
    verified: true,
    profileImage: "ND",
    portfolio: [],
    idDocument: "verified_id_004.pdf",
    qualificationDocuments: ["cleaning_certification.pdf"],
    verificationStatus: "approved",
    verificationNotes: "Professional cleaning certification verified",
    verifiedAt: new Date().toISOString(),
    approvalStatus: "approved",
    subscriptionTier: "verified"
  },
  {
    firstName: "David",
    lastName: "Van Der Merwe",
    email: "david.vandermerwe@email.com",
    phone: "+27 85 456 7890",
    location: "Stellenbosch, Western Cape",
    services: ["carpenters"],
    description: "Custom furniture maker and carpenter with expertise in kitchen cabinets and built-in storage solutions.",
    yearsExperience: 20,
    rating: "3.8",
    reviewCount: 15,
    verified: false,
    profileImage: "DV",
    portfolio: [],
    idDocument: null,
    qualificationDocuments: [],
    verificationStatus: "pending",
    verificationNotes: null,
    verifiedAt: null,
    approvalStatus: "approved",
    subscriptionTier: "unverified"
  },
  {
    firstName: "Zanele",
    lastName: "Mbeki",
    email: "zanele.mbeki@email.com",
    phone: "+27 86 567 8901",
    location: "Port Elizabeth, Eastern Cape",
    services: ["landscapers"],
    description: "Landscape designer creating beautiful outdoor spaces with indigenous plants and sustainable design principles.",
    yearsExperience: 10,
    rating: "4.1",
    reviewCount: 19,
    verified: false,
    profileImage: "ZM",
    portfolio: [],
    idDocument: null,
    qualificationDocuments: [],
    verificationStatus: "pending",
    verificationNotes: null,
    verifiedAt: null,
    approvalStatus: "approved",
    subscriptionTier: "unverified"
  },
  {
    firstName: "Ahmed",
    lastName: "Hassan",
    email: "ahmed.hassan@email.com",
    phone: "+27 87 678 9012",
    location: "Johannesburg, Gauteng",
    services: ["tilers"],
    description: "Specialist in ceramic, porcelain, and natural stone tiling for bathrooms, kitchens, and commercial spaces.",
    yearsExperience: 14,
    rating: "3.9",
    reviewCount: 22,
    verified: false,
    profileImage: "AH",
    portfolio: [],
    idDocument: null,
    qualificationDocuments: [],
    verificationStatus: "pending",
    verificationNotes: null,
    verifiedAt: null,
    approvalStatus: "approved",
    subscriptionTier: "unverified"
  }
];

export async function seedDatabase() {
  try {
    console.log("Seeding database...");
    
    // Check if artisans already exist
    const existingArtisans = await db.select().from(artisans);
    
    if (existingArtisans.length < 10) {
      // Add original sample artisans
      await db.insert(artisans).values(sampleArtisans);
      console.log(`Seeded ${sampleArtisans.length} original artisans`);
    }
    
    if (existingArtisans.length < 30) {
      // Add Gauteng artisans
      await db.insert(artisans).values(gautengArtisans);
      console.log(`Seeded ${gautengArtisans.length} Gauteng artisans`);
    }
    
    const finalCount = await db.select().from(artisans);
    console.log(`Database now has ${finalCount.length} total artisans`);
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}