extend type DiaryEntry {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "DiaryEntry", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `DiaryEntry`.`mood`. It must match the value of `Mood`.`id`. See `@ref` for how to customize it.
  """
  moodId: UUID @fdc_generated(from: "DiaryEntry.mood", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `DiaryEntry`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID @fdc_generated(from: "DiaryEntry.user", purpose: IMPLICIT_REF_FIELD)
}
extend type DiaryEntryTag {
  """
  ✨ Implicit foreign key field based on `DiaryEntryTag`.`diaryEntry`. It must match the value of `DiaryEntry`.`id`. See `@ref` for how to customize it.
  """
  diaryEntryId: UUID! @fdc_generated(from: "DiaryEntryTag.diaryEntry", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `DiaryEntryTag`.`tag`. It must match the value of `Tag`.`id`. See `@ref` for how to customize it.
  """
  tagId: UUID! @fdc_generated(from: "DiaryEntryTag.tag", purpose: IMPLICIT_REF_FIELD)
}
extend type Mood {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Mood", purpose: IMPLICIT_KEY_FIELD)
}
extend type Tag {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Tag", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Tag`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID @fdc_generated(from: "Tag.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
