extend type Query {
  """
  ✨ Look up a single `DiaryEntry` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  diaryEntry(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DiaryEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DiaryEntry_FirstRow
  ): DiaryEntry @fdc_generated(from: "DiaryEntry", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DiaryEntryTag` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  diaryEntryTag(
    """
    The key used to identify the object.
    """
    key: DiaryEntryTag_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DiaryEntryTag_FirstRow
  ): DiaryEntryTag @fdc_generated(from: "DiaryEntryTag", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Mood` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  mood(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Mood_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Mood_FirstRow
  ): Mood @fdc_generated(from: "Mood", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Tag` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  tag(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Tag_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tag_FirstRow
  ): Tag @fdc_generated(from: "Tag", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `DiaryEntry` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  diaryEntries(
    """
    Filter condition to narrow down the query results.
    """
    where: DiaryEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DiaryEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DiaryEntry_Having
  ): [DiaryEntry!]! @fdc_generated(from: "DiaryEntry", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DiaryEntryTag` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  diaryEntryTags(
    """
    Filter condition to narrow down the query results.
    """
    where: DiaryEntryTag_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DiaryEntryTag_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DiaryEntryTag_Having
  ): [DiaryEntryTag!]! @fdc_generated(from: "DiaryEntryTag", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Mood` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  moods(
    """
    Filter condition to narrow down the query results.
    """
    where: Mood_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Mood_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Mood_Having
  ): [Mood!]! @fdc_generated(from: "Mood", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Tag` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tags(
    """
    Filter condition to narrow down the query results.
    """
    where: Tag_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Tag_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Tag_Having
  ): [Tag!]! @fdc_generated(from: "Tag", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
